# Generated by Django 5.1.3 on 2024-11-15 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='blog_commen_user_id_88a23e_idx',
        ),
        migrations.RemoveIndex(
            model_name='postview',
            name='blog_postvi_user_id_9c880f_idx',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='website',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='bookmarks',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='postview',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
