# Generated by Django 5.1.3 on 2026-04-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_newsletter_options_remove_newsletter_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
