# Generated by Django 5.0.2 on 2024-04-29 15:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='intro',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
